<?php
return array(	
	'goods' =>array('name' => '商品', 'icon'=>'ico-goods', 'child' => array(
//			array('name' => '平台商品', 'act'=>'platformGoods', 'op'=>'Goods'),
			array('name' => '商品发布', 'act'=>'addStepOne', 'op'=>'Goods'),
			array('name' => '淘宝导入', 'act'=>'index', 'op'=>'Import'), //临时屏蔽淘宝商品导入
			array('name' => '商品Excel导入/导出', 'act'=>'excel_index', 'op'=>'Import'),
			array('name' => '出售中的商品', 'act'=>'goodsList', 'op'=>'Goods'),
			array('name' => '仓库中的商品', 'act'=>'goods_offline', 'op'=>'Goods'),
			array('name' => '供应商品', 'act'=>'dealerGoodsList', 'op'=>'Goods'),
			array('name' => '库存管理', 'act'=>'stock_list', 'op'=>'Goods'),
			array('name' => '商品规格', 'act' => 'specList', 'op'=>'Goods'),
			array('name' => '品牌管理', 'act'=>'brandList', 'op'=>'Goods'),
     	    array('name' => '相册管理', 'act'=>'albumList', 'op'=>'Goods'),
	)),
	'order'=>array('name' => '订单物流', 'icon'=>'ico-order', 'child' => array(
			array('name' => '订单列表', 'act'=>'index', 'op'=>'Order'),
			array('name' => '虚拟订单', 'act'=>'virtual_list', 'op'=>'Order'),
			array('name' => '拼团列表', 'act'=>'team_list', 'op'=>'Order'),
			array('name' => '拼团订单', 'act'=>'team_order', 'op'=>'Order'),
			array('name' => '供应商订单', 'act'=>'dealerOrderList', 'op'=>'Order'),
			array('name' => '发货商品', 'act'=>'delivery_list', 'op'=>'Order'),
			array('name' => '批量发货', 'act'=>'delivery_excel', 'op'=>'Order'),
			array('name' => '运费模板', 'act'=>'index', 'op'=>'Freight'),
			array('name' => '商品评论','act'=>'index','op'=>'Comment'),
			array('name' => '发票列表','act'=>'index','op'=>'Invoice'),
			array('name' => '快递公司', 'act'=>'index', 'op'=>'Shipping'),
			array('name' => '上门自提', 'act'=>'index', 'op'=>'ShopOrder'),
	)),
	'promotion' => array('name' => '促销', 'icon'=>'ico-promotion', 'child' => array(
			array('name' => '抢购管理', 'act'=>'flash_sale', 'op'=>'Promotion'),
			array('name' => '团购管理', 'act'=>'group_buy_list', 'op'=>'Promotion'),
			array('name' => '商品促销', 'act'=>'prom_goods_list', 'op'=>'Promotion'),
			array('name' => '订单促销', 'act'=>'prom_order_list', 'op'=>'Promotion'),
			array('name' => '拼团管理', 'act'=>'index', 'op'=>'Team'),
			array('name' => '预售管理', 'act'=>'index', 'op'=>'PreSell'),
			array('name' => '砍价管理', 'act'=>'index', 'op'=>'PromotionBargain'),
			array('name' => '代金券管理','act'=>'index', 'op'=>'Coupon'),
	)),
	'store' => array('name' => '店铺', 'icon'=>'ico-store', 'child' => array(
			array('name' => '店铺设置', 'act'=>'store_setting', 'op'=>'Store'),
			array('name' => '店铺装修', 'act'=>'store_decoration', 'op'=>'Store'),
			//array('name' => '移动端店铺首页', 'act'=>'template_index', 'op'=>'Store'),
			//array('name' => '店铺自定义页面', 'act'=>'mobile_template', 'op'=>'Store'),
			array('name' => '店铺导航', 'act'=>'navigation_list', 'op'=>'Store'),
			array('name' => '经营类目', 'act'=>'bind_class_list', 'op'=>'Store'),
			//array('name' => '关联版式', 'act'=>'plate_list', 'op'=>'Store'),
			array('name' => '店铺信息', 'act'=>'store_info', 'op'=>'Store'),
			array('name' => '店铺分类', 'act'=>'goods_class', 'op'=>'Store'),
			//array('name' => '供货商', 'act'=>'suppliers_list', 'op'=>'Store'),
			array('name' => '店铺关注', 'act'=>'store_collect', 'op'=>'Store'),
			array('name' => '消费者保障服务', 'act'=>'index', 'op'=>'Guarantee'),
			array('name' => '地址管理', 'act'=>'index', 'op'=>'Address'),
			array('name' => '我的供应商', 'act'=>'supplier_list', 'op'=>'Store'),
			array('name' => '新闻列表', 'act'=>'index', 'op'=>'News'),

    )),
	
	'shop' => array('name' => '门店', 'icon'=>'ico-store', 'child' => array(
			array('name' => '门店管理', 'act'=>'index', 'op'=>'Shop'),
//			array('name' => '门店订单统计', 'act'=>'order', 'op'=>'Shop'),
	)),
	
	'consult' => array('name' => '售后服务', 'icon'=>'ico-store', 'child' => array(
			array('name' => '咨询管理', 'act'=>'ask_list', 'op'=>'Service'),
			array('name' => '退货换货', 'act'=>'refund_list', 'op'=>'Service'),
			array('name' => '投诉管理', 'act'=>'complain_list', 'op'=>'Service'),
	)),
	'statistics' => array('name' => '统计结算', 'icon'=>'ico-statistics', 'child' => array(
			array('name' => '提现申请', 'act'=>'withdrawals', 'op'=>'Finance'),
			array('name' => '汇款列表', 'act'=>'remittance', 'op'=>'Finance'),
			array('name' => '店铺结算记录', 'act'=>'order_statis', 'op'=>'Finance'),
			array('name' => '未结算订单', 'act'=>'order_no_statis', 'op'=>'Finance'),
			array('name' => '店铺概况', 'act'=>'index', 'op'=>'Report'),
			array('name' => '运营报告', 'act'=>'finance', 'op'=>'Report'),
			array('name' => '销售排行', 'act'=>'saleTop', 'op'=>'Report'),
			//array('name' => '流量统计', 'act'=>'visit', 'op'=>'Report'),
	)),
	'message' => array('name' => '客服消息', 'icon'=>'ico-message', 'child' => array(
			array('name' => '客服设置', 'act'=>'store_service', 'op'=>'Index'),
			array('name' => '系统消息', 'act'=>'store_msg', 'op'=>'Index'),
			//array('name' => '聊天记录查询', 'act'=>'store_im', 'op'=>'store'),
	)),
	'account' => array('name' => '账号', 'icon'=>'ico-account', 'child' => array(
			array('name' => '店长二维码', 'act'=>'store_qrcode', 'op'=>'Admin'),
			array('name' => '账号列表', 'act'=>'index', 'op'=>'Admin'),
			array('name' => '账号组', 'act'=>'role', 'op'=>'Admin'),
			array('name' => '账号日志', 'act'=>'log', 'op'=>'Admin'),
			//array('name' => '店铺消费', 'act'=>'store_cost', 'op'=>'cost_list'),
            //array('name' => '门店账号', 'act'=>'store_account', 'op'=>'index'),
	)),
	'service' => array('name' => '分销', 'icon'=>'ico-live', 'child' => array(
			array('name' => '店铺会员', 'act'=>'store_member', 'op'=>'Distribut'),
			array('name' => '会员店铺', 'act'=>'member_store', 'op'=>'Distribut'),
			array('name' => '分销商品', 'act'=>'goods_list', 'op'=>'Distribut'),
			array('name' => '分销设置', 'act'=>'distribut', 'op'=>'Distribut'),
			array('name' => '分成记录', 'act'=>'rebate_log', 'op'=>'Distribut'),
	)),
	'supplier' => array('name' => '供应商', 'icon'=>'ico-live', 'child' => array(
			array('name' => '我的销售商', 'act'=>'dealer_list', 'op'=>'Store'),
			array('name' => '供应商品', 'act'=>'supplierGoodsList', 'op'=>'Goods'),
			array('name' => '库存管理', 'act'=>'supplierStockList', 'op'=>'Goods'),
			array('name' => '供应商订单', 'act'=>'supplierOrderList', 'op'=>'Order'),
			array('name' => '发货商品', 'act'=>'supplierDeliveryList', 'op'=>'Order'),
			array('name' => '发票列表', 'act'=>'supplierInvoiceList', 'op'=>'Invoice'),
			array('name' => '退货换货', 'act'=>'supplierRefundList', 'op'=>'Service'),
	)),
);