<?php
/**
 * tpshop
 * ============================================================================
 * * 版权所有 2015-2027 深圳搜豹网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.tp-shop.cn
 * ----------------------------------------------------------------------------
 * 商业用途务必到官方购买正版授权, 使用盗版将严厉追究您的法律责任。
 * 采用最新Thinkphp5助手函数特性实现单字母函数M D U等简写方式
 * ============================================================================
 * $Author: 当燃 2016-01-09
 */

namespace app\mobile\controller;

use app\common\model\Shop;
use app\common\model\ShopGoodsStock;
use app\common\logic\CartLogic;
use app\common\logic\CouponLogic;
use think\Db;
use think\Model;
use think\Page;

/**
 * o2o
 * Class Offline
 * @package app\mobile\controller
 */
class Offline extends MobileBase
{
    private $shopModel;
    private $user_id=0;
    private $user;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (session('?user')) {
            $user = session('user');
            session('user', $user);  //覆盖session 中的 user
            $this->user = $user;
            $this->user_id = $user['user_id'];
        }
        $this->shopModel = new Shop();
    }

    public function index(){
        //秒杀商品
        $now_time = time();  //当前时间
        if (is_int($now_time / 7200)) {      //双整点时间，如：10:00, 12:00
            $start_time = $now_time;
        } else {
            $start_time = floor($now_time / 7200) * 7200; //取得前一个双整点时间
        }
        $end_time = $start_time + 7200;   //结束时间
        $this->assign('end_time', $end_time);
        return $this->fetch();
    }

    /**
     * 获取临近店铺
     */
    public function getNearbyShop(){
        $shopList = [];
        $lon =trim(input('lon',114.067345));  //经度
        $lat =trim(input('lat',22.632611));    //纬度
        $scope = 10000; //查找范围(千米)
        $shop_where = "shop_recommend=1 and shop_status=1 and deleted=0 and SQRT((POW((($lon - longitude)* 111),2))+(POW((($lat - latitude)* 111),2))) <=$scope";
        $count_shop = $this->shopModel->where($shop_where)->count();
        $Page = new Page($count_shop,10);
        $shopListObj = $this->shopModel->field("*,round(SQRT((POW((($lon - longitude)* 111),2))+(POW((($lat - latitude)* 111),2))),2) AS distance")->where($shop_where)->limit($Page->firstRow,$Page->listRows)->select();  //带距离参数的数据
        if ($shopListObj){
            $shopList = collection($shopListObj)->append(['shop_prom'])->toArray();
        }
        $type = ['折','减','惠','赠'];
        $this->assign('type',$type);
        $this->assign('shopList',$shopList);
        return $this->fetch();
    }

    /**
 * 门店商品
 * @return mixed
 */
    public function shop(){
        $shop_id = input('shop_id/d',0);
        $shopObj = $this->shopModel->where(['deleted'=>0,'shop_id'=>$shop_id])->find();
        if (!$shopObj){
            $this->error('店铺不存在！！');
        }
        $shop_info = $shopObj->append(['shop_prom','coupon','address_region'])->toArray();
        $goods_class = Db::name('store_goods_class')->where(['parent_id'=>0,'store_id'=>$shop_info['store_id']])->select();  //本店1级分类
        $this->assign('goods_class',$goods_class);
        $type = ['折','减','惠','赠'];
        $this->assign('type',$type);
        $this->assign('shop_info',$shop_info);
        return $this->fetch();
    }

    /**
     * 门店商品
     * @return mixed
     */
    public function getGoods(){
        $user_id = $this->user_id;
        if ($user_id == 0){
            $this->ajaxReturn(['status'=>-1,'msg'=>'请先登录！！']);
        }
        $shopGoodsStockModel = new shopGoodsStock();
        $shop_id = input('shop_id/d',0);
        $cat_id = input('cat_id/d',0);
        $where = ['sg.shop_id'=>$shop_id,];
        if ($cat_id){
            $where['g.cat_id1']=$cat_id;
        }else{
            $where['g.is_hot']=1;
        }
        $count = $shopGoodsStockModel->alias('sg')
            ->join('goods g','g.goods_id=sg.goods_id','left')->where($where)->count();
        $Page= new Page($count,5);
        $shopGoodsStockObj = $shopGoodsStockModel->alias('sg')
            ->join('goods g','g.goods_id=sg.goods_id','left')->where($where)->limit($Page->firstRow,$Page->listRows)->select();
        $shop_goods_stock = [];
        if ($shopGoodsStockObj){
            $shopGoodsStockModel->setUserID($user_id);
            $shopGoodsStockModel->setShopID($shop_id);
            $shop_goods_stock = collection($shopGoodsStockObj)->append(['spec','goods_cart_info'])->toArray();
        }
        $this->ajaxReturn(['status'=>1,'msg'=>'获取成功！！','restut'=>$shop_goods_stock]);
    }

    /**
     * 门店评价详情
     * @return mixed
     */
    public function comment(){
        $shop_id = input('shop_id/d',0);
        $shop_info = Db::name('shop')->where(['deleted'=>0,'shop_id'=>$shop_id])->find();
        $shop_info['shop_comprehensive_credit'] = ($shop_info['shop_desccredit']+$shop_info['shop_servicecredit'])/2;
        $this->assign('shop_info',$shop_info);
        return $this->fetch();
    }

    /**
     * 门店详情
     * @return mixed
     */
    public function info(){
        $shop_id = input('shop_id/d',0);
        $shop_info = Db::name('shop')->where(['deleted'=>0,'shop_id'=>$shop_id])->find();
        $this->assign('shop_info',$shop_info);
        return $this->fetch();
    }

    /**
     * 门店购物车
     * @return mixed
     */
    public function getShopCart(){
        $user_id = $this->user_id;
        $shop_id = I('shop_id/d');
        if ($user_id == 0){
            $this->ajaxReturn(['status'=>-1,'msg'=>'请先登录！！']);
        }
        $cartLogic = new CartLogic();
        $cartLogic->setUserId($user_id);
        $cartLogic->setShopId($shop_id);
        $cartList['cartList'] = $cartLogic->getCartList(1); // 获取用户选中的购物车商品
        $cartList['total_num'] = array_sum(array_map(function($val){return $val['goods_num'];}, $cartList['cartList']));//购物车购买的商品总数
        $cartList['total_fee'] = array_sum(array_map(function($val){return $val['member_goods_price'];}, $cartList['cartList']));//购物车购买的商品总数
        $this->ajaxReturn(['status'=>1,'msg'=>'获取成功！！','result'=>$cartList]);
    }
}